# Generated by Django 3.0.8 on 2020-07-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokebotweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokestorage',
            old_name='secondPhrase',
            new_name='fullJoke',
        ),
        migrations.RemoveField(
            model_name='jokestorage',
            name='jokeCount',
        ),
    ]
